### ISSUE TITLE
무한 스크롤

### ISSUE THREAD

**Issue by jinmayamashita** [KiD-repo/suite#5]
페이지값을 어떻게 유지할 것인가?(page, searchType, keyword)

**Comment by jzinma** [comment]
### 무한 스크롤 > 상세 페이지 > 목록으로 > 보던 페이지로 돌아갈수 있게 처리예정
- 목록 버튼을 누르면 보고 있던 이전 페이지 무한 스크롤로 돌아가기
- 브라우저 뒤로 가는거랑 똑 같이.

**Comment by jinmayamashita** [comment]
버그있음:
진입시, 1페이지 , 누르면 1페이지 , 한번 더 누르면 2페이지. 로직 확인 필요.

LIST MORE = 1 > 1 > 2

**Comment by jinmayamashita** [comment]
마지막 페이지에서는 마지막 페이지라는 메시지 필요. (마지막 페이지는 요청시 data.length등으로 개수 확인)
