### ISSUE TITLE
닉네임 검색 이슈

### ISSUE THREAD

**Issue by zzinpan** [KiD-repo/suite#6]
현재 페이스북 닉네임을 게시판에 표기하게 되어있음.

다른 사용자가 그 닉네임을 검색어로 검색할 경우 ?

페이스북에 graph search기능이 있지만 
해당 닉네임을 사용하는 모든 유저의 고유 식별 아이디를 가져온다.

글쓴이 검색 대안이 필요

**Comment by jzinma** [comment]
글쓴이 검색을 폐기. 대안으로 하기의 기능 추가 예정.

- 현재 보고 있는 글의 유저의 다른 글을 표시 기능
- 보고 있는 글을 빠르게 저장하고 싶을때 원클릭으로 내 박스에 저장 가능 기능
